// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlwwhHHpdc3OoGIAZgl6RWJb6J824SWiE',
    appId: '1:291576166539:web:0763de67e745f97d68fc8e',
    messagingSenderId: '291576166539',
    projectId: 'login-cb7d4',
    authDomain: 'login-cb7d4.firebaseapp.com',
    storageBucket: 'login-cb7d4.appspot.com',
    measurementId: 'G-5SC397T25Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkrOoB1TyT5LEolqHmfpZk5A5B7ewFuUg',
    appId: '1:291576166539:android:99b8a84ac52d872068fc8e',
    messagingSenderId: '291576166539',
    projectId: 'login-cb7d4',
    storageBucket: 'login-cb7d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFN1mJWg_4yLcyiAPgGMdWWow62-3lrLk',
    appId: '1:291576166539:ios:de9f04524b78f81568fc8e',
    messagingSenderId: '291576166539',
    projectId: 'login-cb7d4',
    storageBucket: 'login-cb7d4.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFN1mJWg_4yLcyiAPgGMdWWow62-3lrLk',
    appId: '1:291576166539:ios:de9f04524b78f81568fc8e',
    messagingSenderId: '291576166539',
    projectId: 'login-cb7d4',
    storageBucket: 'login-cb7d4.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlwwhHHpdc3OoGIAZgl6RWJb6J824SWiE',
    appId: '1:291576166539:web:aebec23ade863df068fc8e',
    messagingSenderId: '291576166539',
    projectId: 'login-cb7d4',
    authDomain: 'login-cb7d4.firebaseapp.com',
    storageBucket: 'login-cb7d4.appspot.com',
    measurementId: 'G-YFB13Z2TSW',
  );
}
